languageCode = "de"
languageName = "Deutsch"
weight = 4
title = "N9O"

[params]
  displayName = "Deutsch"
  isoCode = "de"
  rtl = false
  dateFormat = "02. January 2006"
  logo = "img/logo_inverted@0.25x.png"
  secondaryLogo = "img/logo@0.25x.png"
  description = "N9O | Nuno Coração"
