languageCode = "es"
languageName = "Español"
weight = 3
title = "N9O"

[params]
  displayName = "Español"
  isoCode = "es"
  rtl = false
  dateFormat = "02 de January de 2006"
  logo = "img/logo_inverted@0.25x.png"
  secondaryLogo = "img/logo@0.25x.png"
  description = "N9O | Nuno Coração"
