languageCode = "it"
languageName = "Italiano"
weight = 6
title = "N9O"

[params]
  displayName = "Italiano"
  isoCode = "it"
  rtl = false
  dateFormat = "2006-01"
  logo = "img/logo_inverted@0.25x.png"
  secondaryLogo = "img/logo@0.25x.png"
  description = "N9O | Nuno Coração"
