languageCode = "fr"
languageName = "Français"
weight = 5
title = "N9O"

[params]
  displayName = "Français"
  isoCode = "fr"
  rtl = false
  dateFormat = "2006-01"
  logo = "img/logo_inverted@0.25x.png"
  secondaryLogo = "img/logo@0.25x.png"
  description = "N9O | Nuno Coração"
