languageCode = "pt-pt"
languageName = "Português"
weight = 2
title = "N9O"

[params]
  displayName = "Português"
  isoCode = "pt-PT"
  rtl = false
  dateFormat = "02 de January de 2006"
  logo = "img/logo_inverted@0.25x.png"
  secondaryLogo = "img/logo@0.25x.png"
  description = "N9O | Nuno Coração"
