languageCode = "zh-CN"
languageName = "简体中文"
weight = 8
title = "N9O"

[params]
  displayName = "简体中文"
  isoCode = "zh-CN"
  rtl = false
  dateFormat = "2006年01月02日"
  logo = "img/logo_inverted@0.25x.png"
  secondaryLogo = "img/logo@0.25x.png"
  description = "N9O | Nuno Coração"
